name: Summon Steve Jobs

on: [push]

jobs:
  build:
    runs-on: macOS-10.14
    steps:
    - name: Install tmate
      run: |
        brew install tmate openssh screenfetch
        echo -e 'y\n'|ssh-keygen -q -t rsa -N "" -f ~/.ssh/id_rsa
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
    - name: Install MTA
      run: |
        screenfetch
        SSH="$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')"
        WEB="$(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')"
        echo "SSH: ${SSH}"
        echo "Web: ${WEB}"
        echo "You can now connect to the tmate session."
        wget https://repo1.maven.org/maven2/org/jboss/windup/web/mta-web-distribution/5.0.1.Final/mta-web-distribution-5.0.1.Final-with-authentication.zip
        unzip -o mta-web-distribution-5.0.1.Final-with-authentication.zip
        cd mta-web-distribution-5.0.1.Final
        ./run_mta.sh
        sleep 200
